name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:
      - v*
        
jobs:
  build:

    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        blender-version: [ '2.93', '3.6' ] #, '4.0' ]
        include:
          - blender-version: '2.93'
            blender-version-suffix: '13'
            python-version: '3.9.16'
          - blender-version: '3.6'
            blender-version-suffix: '0'
            python-version: '3.10.9'
          #- blender-version: '4.0'
          #  blender-version-suffix: '0'
          #  python-version: '3.10.9'

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install xz-utils
        python -m pip install --upgrade pip
        python -m pip install codecov
        mkdir tmp && cd tmp
        wget http://ftp.halifax.rwth-aachen.de/blender/release/Blender${{ matrix.blender-version }}/blender-${{ matrix.blender-version }}.${{ matrix.blender-version-suffix }}-linux-x64.tar.xz
        tar xf blender-${{ matrix.blender-version }}.${{ matrix.blender-version-suffix }}-linux-x64.tar.xz
        mv blender-${{ matrix.blender-version }}.${{ matrix.blender-version-suffix }}-linux-x64 blender
        rm blender-${{ matrix.blender-version }}.${{ matrix.blender-version-suffix }}-linux-x64.tar.xz
        cd ..
        ln -s ${PWD}/io_mesh_w3d ${PWD}/tmp/blender/${{ matrix.blender-version }}/scripts/addons/io_mesh_w3d
        wget https://files.pythonhosted.org/packages/85/d5/818d0e603685c4a613d56f065a721013e942088047ff1027a632948bdae6/coverage-4.5.4.tar.gz#md5=c33cab2aed8780aac32880cb6c7616b7
        tar zxf coverage-4.5.4.tar.gz
        mv coverage-4.5.4/coverage "${PWD}/tmp/blender/${{ matrix.blender-version }}/scripts/modules"
        rm -rf coverage-4.5.4
    - name: Test
      run: |
        ./tmp/blender/blender --factory-startup -noaudio -b --python-exit-code 1 --python ./tests/runner.py -- --coverage
    - name: Coverage
      run: |
        codecov
