name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        python-version: [ '3.7' ]
        blender-version: ['2.83', '2.90', '2.91' ]
        include:
          - blender-version: '2.83'
            blender-version-suffix: '5'
          - blender-version: '2.90'
            blender-version-suffix: '0'
          - blender-version: '2.91'
            blender-version-suffix: '0'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install xz-utils
        python -m pip install --upgrade pip
        python -m pip install codecov
        mkdir tmp && cd tmp
        wget http://ftp.halifax.rwth-aachen.de/blender/release/Blender${{ matrix.blender-version }}/blender-${{ matrix.blender-version }}.${{ matrix.blender-version-suffix }}-linux64.tar.xz
        tar xf blender-${{ matrix.blender-version }}.${{ matrix.blender-version-suffix }}-linux64.tar.xz
        mv blender-${{ matrix.blender-version }}.${{ matrix.blender-version-suffix }}-linux64 blender
        rm blender-${{ matrix.blender-version }}.${{ matrix.blender-version-suffix }}-linux64.tar.xz
        cd ..
        ln -s ${PWD}/io_mesh_w3d ${PWD}/tmp/blender/${{ matrix.blender-version }}/scripts/addons/io_mesh_w3d
        wget https://files.pythonhosted.org/packages/85/d5/818d0e603685c4a613d56f065a721013e942088047ff1027a632948bdae6/coverage-4.5.4.tar.gz#md5=c33cab2aed8780aac32880cb6c7616b7
        tar zxf coverage-4.5.4.tar.gz
        mv coverage-4.5.4/coverage "${PWD}/tmp/blender/${{ matrix.blender-version }}/python/lib/python${{ matrix.python-version }}"
        rm -rf coverage-4.5.4
    - name: Test
      run: |
        ./tmp/blender/blender --factory-startup -noaudio -b --python-exit-code 1 --python ./tests/runner.py -- --coverage
    - name: Coverage
      run: |
        codecov

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    runs-on: [ ubuntu-latest ]

    steps:
    - name: Bundle archive
      run: |
        zip -r io_mesh_w3d.zip io_mesh_w3d

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: "TODO: add relase notes ."
        draft: false
        prerelease: true