name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        python-version: [ '3.7' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install xz-utils
        python -m pip install --upgrade pip
        python -m pip install codecov
        mkdir tmp && cd tmp
        wget http://ftp.halifax.rwth-aachen.de/blender/release/Blender2.90/blender-2.90.0-linux64.tar.xz
        tar xf blender-2.90.0-linux64.tar.xz
        mv blender-2.90.0-linux64 blender
        rm blender-2.90.0-linux64.tar.xz
        cd ..
        ln -s ${PWD}/io_mesh_w3d ${PWD}/tmp/blender/2.90/scripts/addons/io_mesh_w3d
        wget https://files.pythonhosted.org/packages/85/d5/818d0e603685c4a613d56f065a721013e942088047ff1027a632948bdae6/coverage-4.5.4.tar.gz#md5=c33cab2aed8780aac32880cb6c7616b7
        tar zxf coverage-4.5.4.tar.gz
        mv coverage-4.5.4/coverage "${PWD}/tmp/blender/2.90/python/lib/python3.7"
        rm -rf coverage-4.5.4
    - name: run tests
      run: |
        ./tmp/blender/blender --factory-startup -noaudio -b --python-exit-code 1 --python ./tests/runner.py -- --coverage
    - name: coverage
      run: |
        codecov
